version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: qwedsa
      POSTGRES_DB: public
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
