import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";

import { Routes } from "@/constants/router";
import { cn } from "@/lib/utils";
import Image from "next/image";
import Link from "next/link";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
        )}
      >
        <Link
          href={Routes.HOME}
          className="w-full flex items-center justify-center py-8"
        >
          <Image
            src="/logo.png"
            alt="Welcome to prne.me - Your Ultimate URL Shortening Solution!"
            title="Welcome to prne.me - Your Ultimate URL Shortening Solution!"
            width={200}
            height={50}
          />
        </Link>
        <main>{children}</main>
      </body>
    </html>
  );
}
